site_name: Alfs notes

plugins:
  - glightbox
  - blogging:
      features:
        tags: {}
      dirs: # The directories to be included
        - blog
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
theme:
  name: material
  features:
    - toc.follow
  language: en # The language your site is written in
  palette:
    primary: 'light blue' # Used as the main color for the site top bar,
                          # links, etc...
    accent: 'deep orange' # Used as the highlight color for the site
  logo: 'assets/logo.png' # This is the location of an image
                          # for use as the site logo in the theme you choose
  favicon: 'assets/favicon.ico' # This is the image used by browsers to identify
                             # your tab to the user

